---
# tasks file for kubeadm-reset
- name: Starting kubeadm reset
  command: kubeadm reset -f
  ignore_errors: yes

- name: Deleteing kube directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/cni/net.d
    - /run/flannel
    - /run/calico

- name: Flushing iptable entries
  iptables:
    flush: yes

- name: cleaning ipvs table
  command: ipvsadm --clear
  ignore_errors: yes

- name: Delete IP link cni0 for flannel
  command: ip link delete cni0
  ignore_errors: yes

- name: Delete IP link flannel.1
  command: ip link delete flannel.1
  ignore_errors: yes

- name: Reboot system for networking bug fix
  reboot: