---
- hosts: all
  become: true
  tasks:
      - name: Enable bridge network traffic
        modprobe:
            name: br_netfilter
            state: present

      - name: Enable bridge network to see ipv6 traffic
        sysctl:
            name: net.bridge.bridge-nf-call-ip6tables
            value: 1
            sysctl_file: /etc/sysctl.d/k8s.conf
            state: present

      - name: Enable bridge network to see ipv4 traffic
        sysctl:
            name: net.bridge.bridge-nf-call-iptables
            value: 1
            sysctl_file: /etc/sysctl.d/k8s.conf
            state: present

      - name: Add Kubernetes repos
        yum_repository:
            name: Kubernetes
            description: Kubernetes repo
            baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
            enabled: yes
            gpgcheck: yes
            repo_gpgcheck: yes
            gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
            exclude: kubelet kubeadm kubectl
            file: kubernetes
            state: present

      - name: Install kubelet and kubeadm package
        yum:
            name: "{{ packages }}"
            state: present
            update_cache: yes
            disable_excludes: Kubernetes
        vars:
            packages:
                - kubelet-{{ k8s_version }}
                - kubeadm-{{ k8s_version }}

- hosts: k8s_master
  become: true
  tasks:
      - name: Install kubectl in k8s  control machine
        yum:
            name: kubectl-{{ k8s_version }}
            state: present
            update_cache: yes
            disable_excludes: Kubernetes
