- hosts: all
  name: Installing Common applications
  become: true
  roles:
    # - crio
    - k8s-common-install

# - hosts: k8s_master
#   name: K8S Control machine setup
#   become: true
#   roles:
#     - k8s-control