- hosts: all
  name: Installing Common applications
  become: true
  roles:
    - crio
    # - k8s-common-install

# - hosts: control_plane
#   name: K8S Control machine setup
#   become: true
#   roles:
#     - k8s-control