- hosts: reset_node
  name: tryout
  become: no
  become_user: "{{ admin_user }}"
  tasks:
    - name: Check if kubeadm has already run
      stat:
          path: "/var/lib/containerd"
      register: container

    - name: check vaar content
      ansible.builtin.debug:
        var: container