crio_os: CentOS_8
crio_version: 1.22

k8s_version: 1.22.5

network_interface: "eth1"

network_cider: 10.244.0.0/16
pod_network_cidr: 10.244.0.0/16
# network_cider: 192.168.0.0/16

admin_user: vagrant
admin_group: vagrant

cni_manifest: https://raw.githubusercontent.com/flannel-io/flannel/v0.18.0/Documentation/kube-flannel.yml
# cni_manifest: https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml

reset_install: true

network: flannel2
network_dir: /etc/kubernetes/network
kubeadmin_config: /etc/kubernetes/admin.conf
