---
- name: Install kubectl in k8s  control machine
  yum:
      name: kubectl-{{ k8s_version }}
      state: present
      disable_excludes: Kubernetes

- name: Kubectl extra setup for usability
  include: kubectl-extras.yml

- name: fetch admin kube config file
  fetch:
      src: /etc/kubernetes/admin.conf
      dest: "{{ playbook_dir }}/install_artifacts"

- name: get reference to kubernetes admin user
  become: no
  user:
      name: "{{ admin_user }}"
      state: present
  register: k8s_admin_user

- name: create .kube folder if not exist
  become: no
  become_user: "{{ admin_user }}"
  command: mkdir -p $HOME/.kube

- name: Copy admin kube config file for user
  copy:
      src: /etc/kubernetes/admin.conf
      dest: "{{ k8s_admin_user.home }}/.kube/config"
      owner: "{{ admin_user }}"
      group: "{{ admin_group }}"
      backup: yes
      remote_src: yes
