---

- name: Initiate kubeadm control machine 
  command: kubeadm init --pod-network-cidr={{ network_cider }} --apiserver-advertise-address={{ ansible_ssh_host }} --apiserver-cert-extra-sans={{ ansible_ssh_host }}

- import_tasks: admin-setup.yml

- ansible.builtin.import_role: 
    name: cni
    
