---
- name: Generate control node joining command
  command: kubeadm token create --print-join-command
  register: kubeadm_join_command

- name: copy the joinning command to local file
  local_action: copy content="{{ kubeadm_join_command.stdout_lines[0] }}" dest="{{ playbook_dir }}/install_artifacts/join-command"