---
# tasks file for k8s-control

- name: Check if kubeadm has already run
  stat:
      path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Init cluster if needed
  import_tasks: control-setup.yml
  when: not kubeadm_ca.stat.exists

# - include: control-setup.yml
- import_tasks: joining-command.yml
