---
# - name: Install fannel
#   become: no
#   become_user: "{{ admin_user }}"
#   command: kubectl apply -f {{ cni_manifest }}

- name: Install Tigera Calico operator
  become: no
  become_user: "{{ admin_user }}"
  command: kubectl apply -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml

- name: Install Calico 
  become: no
  become_user: "{{ admin_user }}"
  command: kubectl apply -f https://projectcalico.docs.tigera.io/manifests/custom-resources.yaml

- name: Reboot system for networking bug fix
  reboot: