---
- name: Adding modules to startup module-load.d/k8s.conf
  copy:
    src: k8s.conf
    dest: /etc/modules-load.d/
    group: root
    owner: root

- name: Enable bridge network traffic
  modprobe:
      name: "{{ item }}"
      state: present
  loop: "{{ lookup('file', 'k8s.conf').splitlines() }}"

- name: Enable bridge network to see network traffic
  sysctl:
      name: "{{ item.key }}"
      value: "{{ item.value }}"
      sysctl_file: /etc/sysctl.d/k8s.conf
      state: present
  loop:
    - { key: "net.bridge.bridge-nf-call-ip6tables", value: 1 }
    - { key: "net.bridge.bridge-nf-call-iptables", value: 1 }
    - { key: "net.ipv4.ip_forward", value: 1 }