---
- name: Adding modules to startup module-load.d/k8s.conf
  copy:
    src: k8s.conf
    dest: /etc/modules-load.d/
    group: root
    owner: root

- name: Enable bridge network traffic
  modprobe:
      name: br_netfilter
      state: present

- name: Enable bridge network to see ipv6 traffic
  sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      sysctl_file: /etc/sysctl.d/k8s.conf
      state: present

- name: Enable bridge network to see ipv4 traffic
  sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      sysctl_file: /etc/sysctl.d/k8s.conf
      state: present

- name: Enable ip forward
  sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_file: /etc/sysctl.d/k8s.conf
      state: present